### ISSUE TITLE
Publish the changes

### ISSUE THREAD

**Issue by ckothari** [ezodude/tabula-js#6]
Can some one publish the changes to npm. Last publish was on 2016-05-29T22:56:28.586Z and few commits have been made after that.

**Comment by kcivey** [comment]
Yes, it would be good to have the updates in the published version.

**Comment by cdtinney** [comment]
I've forked and published a new package with some other changes:

https://www.npmjs.com/package/fresh-tabula-js

**Comment by ezodude** [comment]
Mucho appreciated!
